PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sc: <http://iiif.io/api/presentation/2#>
PREFIX oa: <http://www.w3.org/ns/oa#>
PREFIX exif: <http://www.w3.org/2003/12/exif/ns#>
PREFIX svcs: <http://rdfs.org/sioc/services#>
PREFIX dctypes: <http://purl.org/dc/dcmitype/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fedora: <http://fedora.info/definitions/v4/repository#>
PREFIX fixme: <http://iiif.io/api/presentation/3#>
CONSTRUCT {?manifest sc:hasSequences ?seqid .
?manifest dcterms:isPartOf ?collection .
?manifest rdfs:label ?manifestlabel .
?manifest rdf:type sc:Manifest .
?seqid rdf:type rdf:List .
?seqid rdf:first ?sequence.
?seqid rdf:rest ?seqrest .
?sequence rdf:type sc:Sequence .
?sequence sc:hasCanvases ?canvaslistid .
?canvaslistid rdf:first ?first .
?canvaslistid rdf:type rdf:List .
?first exif:height ?height .
?first exif:width ?width .
?first sc:hasImageAnnotations ?firstanno .
?firstanno rdf:type rdf:List .
?firstanno rdf:first ?firstresid .
?firstanno rdf:rest ?firstresrest .
?firstresid rdf:type oa:Annotation.
?firstresid  oa:hasBody ?firstimage .
?firstresid oa:motivatedBy sc:painting .
?firstimage svcs:has_service ?firstservice .
?firstservice fixme:context <http://iiif.io/api/image/2/context.json> .
?firstimage rdf:type dctypes:Image .
?first sc:hasLists ?firstlist .
?canvas rdf:type sc:Canvas .
?canvas exif:height ?height  .
?canvas exif:width ?width  .
?canvaslistid rdf:rest ?mid .
?mid rdf:rest ?node .
?node rdf:first ?canvas .
?node rdf:rest ?last .
?canvas sc:hasImageAnnotations ?annoid  .
?canvas sc:hasLists ?list .
?annoid rdf:first ?resid .
?annoid rdf:rest ?rest .
?resid rdf:type oa:Annotation.
?resid oa:hasBody ?image .
?resid oa:motivatedBy sc:painting .
?image svcs:has_service ?service .
?service fixme:context <http://iiif.io/api/image/2/context.json> .
?image rdf:type dctypes:Image .
}

WHERE { values ?manifest { <http://localhost:8080/fcrepo/rest/collection/AIG/702/manifest> }.
?manifest sc:hasSequences ?seqid .
?manifest rdfs:label ?manifestlabel .
?manifest dcterms:isPartOf ?collection .
?seqid rdf:first ?sequence .
?seqid rdf:rest ?seqrest .
?sequence sc:hasCanvases ?canvaslistid .
values ?e { rdf:first rdf:rest }
?canvaslistid (rdf:rest|rdf:first)* ?mid . ?mid ?e ?node FILTER (?mid != ?node). FILTER (?canvaslistid != ?node).
?canvaslistid rdf:first ?first .
?first sc:hasImageAnnotations ?firstanno .
?first sc:hasLists ?firstlistid .
?firstlistid rdf:first ?firstlist .
?firstanno rdf:first ?firstresid .
?firstanno rdf:rest ?firstresrest .
?firstresid  oa:hasBody ?firstimage .
?firstimage svcs:has_service ?firstservice .
?first exif:height ?height .
?first exif:width ?width .
?node rdf:first ?canvas .
?node rdf:rest ?last .
?canvas sc:hasImageAnnotations ?annoid .
?canvas sc:hasLists ?listid .
?listid rdf:first ?list .
?canvas exif:height ?height .
?canvas exif:width ?width .
?annoid rdf:first ?resid .
?resid  oa:hasBody ?image .
?image svcs:has_service ?service .
?annoid rdf:rest ?rest}
group by ?manifest ?manifestlabel ?collection ?node ?canvas ?image ?canvaslistid ?mid ?annoid ?resid ?rest ?seqid
?sequence ?first ?height ?width ?firstimage ?firstresid ?firstanno ?firstlist ?list ?service ?firstservice ?canvaslabel
?firstlabel ?seqrest ?firstresrest ?last ORDER BY (?canvas)